import {FineUploader, UIOptions} from 'fine-uploader';
import DomElements               from "../../core/utils/DomElements";
import Selectize                 from "../selectize/Selectize";
import Tippy                     from "../tippy/Tippy";
import BootstrapNotify from "../bootstrap-notify/BootstrapNotify";

require('fine-uploader/fine-uploader/fine-uploader.min.css');

/**
 * @description this class handles the upload via jquery by using the package:
 * @link https://www.npmjs.com/package/fine-uploader
 * @link https://docs.fineuploader.com/quickstart/03-setting_up_server.html
 * @link https://docs.fineuploader.com/api/events.html
 * @link https://docs.fineuploader.com/api/methods.html
 */
export default class FineUploaderService
{

    /**
     * @type FineUploader
     */
    private fineUploaderInstance;

    private selectize = new Selectize();

    private bootstrapNotify = new BootstrapNotify();

    // todo: this will be used to track unique files in upload
    //  needs to be updated with MutationObserver or something - that is when user renames the filename then this must be also updated
    private uploadedFilesNames = [];

    public static readonly selectors = {
        fineUploadPanelSelector       : '[data-is-fine-upload]',
        triggerManualUploadButton     : '.trigger-manual-upload',
        filenameEditButton            : '.qq-edit-filename-icon-selector',
        uploadList                    : '.qq-upload-list',
        fontawesomeUploadCancelButton : '.qq-upload-cancel-icon',
        fineUploadCancelButton        : '.qq-upload-cancel-selector',
        tagsInputSelector             : 'input.tags'
    }

    public static readonly attributes = {
        uploadEndpointUrl    : 'data-upload-endpoint-url',
        successFileUploadUrl : 'data-success-file-upload-url',
        uniqueFileIdentifier : 'data-unique-file-identifier',
    }

    /**
     * @description will initialize the logic of the file uploader
     */
    public init(): void
    {
        let _this                = this;
        let $allFineUploadPanels = $(FineUploaderService.selectors.fineUploadPanelSelector);

        if( DomElements.doElementsExists($allFineUploadPanels) ){
            $.each($allFineUploadPanels, (index, element) => {

                let $element = $(element);

                let uploadEndpointUrl     = $element.attr(FineUploaderService.attributes.uploadEndpointUrl);
                let successFileUploadUrl  = $element.attr(FineUploaderService.attributes.successFileUploadUrl);

                let options = {
                   element: element,
                   request: {
                        endpoint: uploadEndpointUrl
                    },
                    chunking: {
                        enabled: true,
                            concurrent: {
                            enabled: true
                        },
                        success: {
                            endpoint: successFileUploadUrl
                        }
                    },
                    resume: {
                        enabled: true
                    },
                    autoUpload: false,
                    callbacks: {
                        /**
                         * @description triggered when file is added to the upload queue
                         */
                        onSubmitted: (uploadedFileId) => {
                            // todo: add logic to deny uploading images with the same name otherwise this won't work
                            //  add warning about not unique name
                            let uploadedFileData           = _this.fineUploaderInstance.getUploads({id: uploadedFileId});
                            let uploadedFileName           = uploadedFileData['name'];
                            let uniqueFileIdentifier       = uploadedFileData['uuid'];
                            let $listElementForCurrentFile = $('[title^="' + uploadedFileName + '"]').closest('li');

                            /**
                             * @description binding the unique record identifier (generated by fine-upload) to the list
                             *              element so that the element can be later on easily tracked
                             */
                            $listElementForCurrentFile.attr(FineUploaderService.attributes.uniqueFileIdentifier, uniqueFileIdentifier);
                        },
                        /**
                         * @description triggered right a moment before when the `upload` process has started for single file
                         */
                        onUpload: (uploadedFileId) => {
                            let uploadedFileData           = _this.fineUploaderInstance.getUploads({id: uploadedFileId});
                            let uniqueFileIdentifier       = uploadedFileData['uuid'];
                            let $listElementForCurrentFile = $("[" + FineUploaderService.attributes.uniqueFileIdentifier + "^='" + uniqueFileIdentifier + "']");
                            let tags                       = $listElementForCurrentFile.find('.tags').val();

                            let uploadModuleDir                = $('#module_and_directory_select_upload_module_dir').val();
                            let targetDirectoryPathInModuleDir = $('#module_and_directory_select_subdirectory').val();

                            let additionalParams = {
                                tags                                          : tags,
                                upload_module_dir                             : uploadModuleDir,
                                subdirectory_target_path_in_module_upload_dir : targetDirectoryPathInModuleDir
                            };
                            _this.handleAdditionalParamsInRequest(additionalParams);
                        },
                        /**
                         * @description triggered when all of the files in upload queue are handled
                         */
                        onAllComplete: (successfullyUploadedFilesIds, failedUploadedFilesIds) => {
                            if( 0 === failedUploadedFilesIds.length ){
                                // todo: success message here
                                this.bootstrapNotify.showGreenNotification("yay");
                            }else{
                                // todo: fail message, could not handle all files
                                this.bootstrapNotify.showRedNotification("nope");
                            }
                        }

                    }
                } as UIOptions;

                // the order is very important here, some logic must be added after the uploader has been initialized
                this.fineUploaderInstance = new FineUploader(options);
                this.handleManualUploadButton();
            })

            this.observerFilesList();
        }

    }

    /**
     * @description will add logic for handling the upload after manually clicking on the upload button
     *
     * @private
     */
    private handleManualUploadButton(): void
    {
        let _this = this;
        // if the upload panel exist then the upload button must be also there
        let $uploadButton = $(FineUploaderService.selectors.triggerManualUploadButton);
        if( !DomElements.doElementsExists($uploadButton) ){
            throw {
                "message"  : "Upload button does not exist for FineUploader template!",
                "selector" : FineUploaderService.selectors.triggerManualUploadButton
            }
        }

        $uploadButton.off('click');
        $uploadButton.on('click', () => {
            _this.fineUploaderInstance.uploadStoredFiles();
        });
    }

    /**
     * @description there is an issue where fontawesome icon steals the click for FineUpload action
     *              this method handles such case and passes the click further to the proper removal button
     */
    private bindRemoveFileFromQueueListOnIconRemovalClick($cancelButtonFontawesome: JQuery, $fineUploadCancelButton: JQuery)
    {
        $cancelButtonFontawesome.on('click', (event) => {
            $fineUploadCancelButton.trigger('click');
        })
    }

    /**
     * @description will observer the uploaded files list, allows to react on adding/changing element etc.
     */
    private observerFilesList(): void
    {
        let $uploadedFilesList = $(FineUploaderService.selectors.uploadList);
        let _this              = this;

        // watch for the list being updated
        let uploadedFilesListObserver = new MutationObserver( (mutations, observer) => {
            let newNodes = mutations[0].addedNodes as Array<HTMLElement>|NodeList;

            for(let listElement of newNodes as Array<HTMLElement>) {
                let $listElement    = $(listElement);
                let $nameEditButton = $listElement.find(FineUploaderService.selectors.filenameEditButton);
                let $inputElements  = $listElement.find('input');

                let $cancelButtonFontawesome = $listElement.find(FineUploaderService.selectors.fontawesomeUploadCancelButton);
                let $fineUploadCancelButton  = $listElement.find(FineUploaderService.selectors.fineUploadCancelButton);

                $nameEditButton.trigger('click');
                $inputElements.blur(); // escape the focus as plugin itself keeps focus upon clicking edit

                _this.handleInitialFilenamesShowingInTheEditInputsByObservingMutations($listElement);
                _this.handleAddingSelectizeTagsForNewInputsByObservingMutations($listElement);
                _this.bindRemoveFileFromQueueListOnIconRemovalClick($cancelButtonFontawesome, $fineUploadCancelButton)
                Tippy.init();
            }
        });

        uploadedFilesListObserver.observe($uploadedFilesList[0], {
            childList: true,
        })
    }

    /**
     * @description the plugin itself works the way that the name is being shown only when we first click
     *              on the edit button but since the input fields is now constantly visible and the edit
     *              button remains hidden - it needs to be `clicked` for each uploaded file
     *
     */
    private handleInitialFilenamesShowingInTheEditInputsByObservingMutations(listElement: JQuery<HTMLElement>): void
    {
        let $listElement    = $(listElement);
        let $nameEditButton = $listElement.find(FineUploaderService.selectors.filenameEditButton);
        let $inputElements  = $listElement.find('input');

        $nameEditButton.trigger('click');
        $inputElements.blur(); // escape the focus as plugin itself keeps focus upon clicking edit
    }

    /**
     * @description upon adding new file the new DOM row is inserted, but each new element need to have selectize tag logic initalized
     *
     */
    private handleAddingSelectizeTagsForNewInputsByObservingMutations(listElement: JQuery<HTMLElement>): void
    {
        let $listElement     = $(listElement);
        let $tagsInput       = $listElement.find(FineUploaderService.selectors.tagsInputSelector);
        let inputHtmlElement = $tagsInput[0];

        this.selectize.applyTagsSelectizeForSingleInput(inputHtmlElement);
    }

    /**
     * @description will add logic for handling the upload after manually clicking on the upload button
     *
     */
    private handleAdditionalParamsInRequest(additionalParams: Object)
    {
        this.fineUploaderInstance.setParams(additionalParams);
    }

}